dbt_sugar:
  target: prod
  outputs:

    prod:
      type: postgres
      host: 127.0.0.1
      user: dbt_sugar
      password: dbt_sugar
      port: 5432
      dbname: dbt_sugar
      schema: public
      threads: 4